[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "faceimagekit"
dynamic = ["version"]
description = "Python implementation of face detection, face landmark, face segmentation and so on."
readme = "README.md"
requires-python = ">=3.8"
license = { text = "AGPL-3.0-only OR Commercial License" }
authors = [{ name = "blakeliu", email = "blake120386@163.com" }]
keywords = ["face detection", "face landmark", "cv", "onnx", "onnxruntime"]
classifiers = [
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: GNU Affero General Public License v3",
    "Operating System :: OS Independent",
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "Intended Audience :: Computer Vision",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Scientific/Engineering :: Computer Vision",
    "Topic :: Face Analysis :: General",
]
dependencies = ["numpy<2", "opencv-python", "numba", "scipy"]

[project.optional-dependencies]
cpu = ["onnxruntime>=1.20.0,<=1.22.0"]
cuda = ["onnxruntime-gpu>=1.20.0,<=1.22.0"]
all = ["onnxruntime>=1.20.0,<=1.22.0"]
dev = ["pytest", "black", "isort", "mypy"]

[project.urls]
"Source" = "https://github.com/blakeliu/CVFaceImgKit.git"
"onnxruntime" = "https://github.com/microsoft/onnxruntime"

[tool.setuptools.dynamic]
version = { attr = "faceimagekit.version.__version__" }

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["faceimagekit*"]
exclude = ["converters*", "examples*"]

[[tool.uv.index]]
name = "aliyun-pypi"
url = "https://mirrors.aliyun.com/pypi/simple"
default = true

[tool.setuptools.package-data]
# Include any data files inside the package
"faceimagekit" = ["py.typed"]

[tool.uv]
# Optional: uv specific settings if needed, but standard standards work best.
